### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by Kefta** [jtsalisbury/gmod12to13-addons#5]
i put in my c drive but its not working??

**Comment by cooljddj** [comment]
Give us something better then C drive, or did you just put in in C:\

**Comment by Kefta** [comment]
@cooljddj

--joke-->

  Head

**Comment by cooljddj** [comment]
so i'm guessing you put it in your addons folder, did you put the zip file in the addons folder or what? please like i said last time explain a bit more

**Comment by Kefta** [comment]
Please go away

**Comment by cooljddj** [comment]
Never.

**Comment by crazyscouter** [comment]
user deleted system 32 everything works now
